"""SendGrid email service for summary delivery."""

import logging
from dataclasses import dataclass

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Content, Email, Mail, To

from src.config.settings import get_settings

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class EmailResult:
    """Immutable email send result."""

    success: bool
    message_id: str | None = None
    error: str | None = None


class EmailService:
    """SendGrid email delivery service."""

    def __init__(self):
        settings = get_settings()
        self._client = SendGridAPIClient(api_key=settings.sendgrid_api_key)
        self._from_email = settings.sendgrid_from_email

    def send_summary(
        self,
        to_email: str,
        call_filename: str,
        summary_text: str,
        key_points: list[str] | None = None,
        action_items: list[str] | None = None,
    ) -> EmailResult:
        """Send call summary via email."""
        subject = f"Call Summary: {call_filename}"

        html_body = self._build_html(
            call_filename=call_filename,
            summary_text=summary_text,
            key_points=key_points or [],
            action_items=action_items or [],
        )

        message = Mail(
            from_email=Email(self._from_email),
            to_emails=To(to_email),
            subject=subject,
            html_content=Content("text/html", html_body),
        )

        try:
            response = self._client.send(message)
            message_id = response.headers.get("X-Message-Id", "")
            logger.info("Email sent to %s (status=%s)", to_email, response.status_code)
            return EmailResult(success=True, message_id=message_id)
        except Exception as e:
            logger.error("Failed to send email to %s: %s", to_email, e)
            return EmailResult(success=False, error=str(e))

    def _build_html(
        self,
        call_filename: str,
        summary_text: str,
        key_points: list[str],
        action_items: list[str],
    ) -> str:
        """Build HTML email body."""
        key_points_html = ""
        if key_points:
            items = "".join(f"<li>{point}</li>" for point in key_points)
            key_points_html = f"<h3>Key Points</h3><ul>{items}</ul>"

        action_items_html = ""
        if action_items:
            items = "".join(f"<li>{item}</li>" for item in action_items)
            action_items_html = f"<h3>Action Items</h3><ul>{items}</ul>"

        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Call Summary: {call_filename}</h2>
            <div style="background: #f5f5f5; padding: 16px; border-radius: 8px; margin: 16px 0;">
                <p>{summary_text}</p>
            </div>
            {key_points_html}
            {action_items_html}
            <hr style="margin-top: 32px;">
            <p style="color: #888; font-size: 12px;">Generated by Calls Summary</p>
        </body>
        </html>
        """
